### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by jurnet** [mondediefr/docker-rutorrent#23]
Bonjour avez vous prévu de mettre en place un docker compose ?

**Comment by Rathorian** [comment]
Bonjour,

Ce n'est pas prévu.
Dans le fichier README.md, tu as pas mal d'informations pour t'aider à utiliser l'image.

Tu as des difficultés ?

**Comment by MisterCyp** [comment]
Voici un exemple: (en plus tout le traffic passe par un VPN)
```
version: "3"
      
services:
  torrent:
    #image: xataz/rtorrent-rutorrent
    image: mondedie/rutorrent:filebot
    restart: always
    container_name: torrent
    network_mode: service:vpn
    deploy:
      resources:
        limits:
          memory: 2G
    environment:
      - FILEBOT_LICENSE=/config/filebot/FileBot_License_PX11888023.psm
      - FILEBOT_RENAME_METHOD=hardlink
      - UID=1026
      - GID=100
      - HTTP_AUTH=true
    volumes:
      - /volume1/homes/Cyprien/config/rutMonDedie/:/config
      - /volume1/homes/Cyprien/Downloads/:/data
      - /run/php:/run/rtorrent
      #- /volume1/homes/Cyprien/config/nginx/:/nginx
      
  vpn:
    image: dperson/openvpn-client
    restart: always
    container_name : vpn
    ports:
      - 8080:8080
    volumes:
      - /volume1/homes/Cyprien/config/vpn/:/vpn
    dns:
      - 208.67.222.222
      - 208.67.220.220
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
```
